fix(scan): instantiate client after computing options
GitGuardian/ggshield pull request #1005
Opened 2024-11-12 16:16 UTC by gg-jonathangriffe

## Context

The `--allow-self-signed` option can theoretically be placed at any level in all `ggshield secret scan` commands, but in practice only when passed just after `ggshield`. This is due to the GGClient being instantiated before taking into account higher level options.

## What has been done

This MR makes the GGClient be instantiated in the command function to fix this issue.

## Validation

Set up a proxy, for example with mitmproxy. To verify that it works, run `ggshield secret scan path <file>`, this should return a certificate error.
Run `ggshield secret scan path <file>`. It should succeed.

## PR check list

- [x] As much as possible, the changes include tests (unit and/or functional)
- [x] If the changes affect the end user (new feature, behavior change, bug fix) then the PR has a changelog entry (see doc/dev/getting-started.md). If the changes do not affect the end user, then the `skip-changelog` label has been added to the PR.

2024-11-13 10:37 UTC, agateau-gg requested changes
Must have been a bit tedious to do 😅.

Looks good overall, just some minor remarks.

2024-11-13 10:37 UTC, agateau-gg commented on changelog.d/20241112_170752_jonathan.griffe_fix_secret_scan_option.md
> +- Take into account --allow-self-signed options at all levels in `ggshield secret scan` commands
```suggestion
- Take into account the `--allow-self-signed` option at all levels in `ggshield secret scan` commands
```

2024-11-13 10:37 UTC, agateau-gg commented on tests/unit/cmd/scan/test_path.py
> +    @pytest.mark.parametrize("verify", [True, False])
Do we care about the case where verify is False? I think it could be more useful to test all possible positions of `--allow-self-signed`.

2024-11-13 17:02 UTC, salome-voltz approved these changes

2024-11-13 17:02 UTC, salome-voltz commented on tests/unit/cmd/scan/test_path.py
> +        print(cmd)
:bomb:

2024-11-14 09:20 UTC, agateau-gg approved these changes

2024-11-14 09:20 UTC, merged