feat(output): Only fail secret scans when the secret is introduced
GitGuardian/ggshield pull request #1010
Opened 2024-11-14 16:54 UTC by Walz

## Context

Related to SPI-526 and will close  #1001

We want to only fail secret scans when the secret is introduced.  
New fields have been added to the API to automatically detect if the content is a diff and if the secret has been added, deleted or in the context. (https://github.com/GitGuardian/py-gitguardian/pull/122)

## What has been done

Make use of the new fields to return success when no secret are added.

TODO: Update the text output.

## Validation

## PR check list

- [ ] As much as possible, the changes include tests (unit and/or functional)
- [ ] If the changes affect the end user (new feature, behavior change, bug fix) then the PR has a changelog entry (see doc/dev/getting-started.md). If the changes do not affect the end user, then the `skip-changelog` label has been added to the PR.

2024-11-19 17:06 UTC, agateau-gg requested changes

2024-11-19 17:06 UTC, agateau-gg commented on ggshield/verticals/secret/secret_scan_collection.py
> +        return policy_breaks
nit: can be slightly simplified to:

```suggestion
        if diff_kinds is not None and self.scan.is_diff:
            return [
                policy_break
                for policy_break in self.scan.policy_breaks
                if policy_break.diff_kind in diff_kinds
            ]
        return self.scan.policy_breaks
```

2024-11-19 17:06 UTC, agateau-gg commented on ggshield/verticals/secret/secret_scan_collection.py
> +        self, *, diff_kinds: Optional[List[DiffKind]] = None
Would be nicer if diff_kinds was a set instead of a list, since we don't want to have duplicate kinds.

2024-11-19 17:06 UTC, agateau-gg commented on ggshield/verticals/secret/secret_scan_collection.py
> +    def policy_breaks(
naming: this should be `get_policy_breaks()`.

2024-11-29 14:57 UTC, Walz commented
Thanks to https://github.com/GitGuardian/ggshield/issues/1001, this PR is a **lot** simpler now.

2024-12-03 13:33 UTC, agateau-gg approved these changes
Nice! And thanks for the great PR description ✨.

2024-12-03 13:33 UTC, merged