Mmillet/spi 515 add all secrets option to ggshield secret scans
GitGuardian/ggshield pull request #1024
Opened 2024-11-27 15:04 UTC by gg-mmill

## Context

## What has been done

## Validation

## PR check list

- [ ] As much as possible, the changes include tests (unit and/or functional)
- [ ] If the changes affect the end user (new feature, behavior change, bug fix) then the PR has a changelog entry (see doc/dev/getting-started.md). If the changes do not affect the end user, then the `skip-changelog` label has been added to the PR.

2024-12-04 17:13 UTC, agateau-gg requested changes
Minor remarks, but this looks good, and the addition of factories is great!

2024-12-04 17:13 UTC, agateau-gg commented on ggshield/core/config/user_config.py
> +                "ignore_known_secrets_secrets": self.show_secrets,
I think this should be:
```suggestion
                "show_secrets": self.show_secrets,
```

2024-12-04 17:45 UTC, gg-mmill commented on ggshield/verticals/secret/secret_scan_collection.py
>      ):
I don't fully understand why, but pyright is unhappy (with `import Self from typing_extensions`):
` - error: Expression of type "Result" is incompatible with return type "Self@Result";`

Using `Result` instead.

2024-12-05 12:37 UTC, gg-mmill commented on ggshield/verticals/secret/secret_scan_collection.py
> +    if policy_break.is_excluded:
Was not on purpose, thanks for noticing !

2024-12-09 10:37 UTC, gg-mmill commented on tests/unit/verticals/secret/test_secret_scan_collection.py
> +        assert (compute_ignore_reason(policy_break, config) is not None) is ignore_known
Had to go with `assert bool(compute_ignore_reason(policy_break, config)) is ignore_known`

2024-12-09 10:55 UTC, merged