pre-commit: fix deprecated stages
GitGuardian/ggshield pull request #1029
Opened 2024-12-05 00:06 UTC by Crocmagnon

Fix #980

## Context

Fix deprecated pre-commit stages.
Fix #980

## Validation

* Create a minimal pre-commit config (see below)
* Run `pre-commit run --all-files`
* No warning should appear.

Minimal config:
```yaml
repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.34.0 # update this version
    hooks:
      - id: ggshield
```

## PR check list

- [x] As much as possible, the changes include tests (unit and/or functional)
- [ ] If the changes affect the end user (new feature, behavior change, bug fix) then the PR has a changelog entry (see doc/dev/getting-started.md). If the changes do not affect the end user, then the `skip-changelog` label has been added to the PR.

❓ Does this require a changelog entry? I'd be tempted to say no but I don't know your policies.

2024-12-05 16:40 UTC, sevbch commented
Hi @Crocmagnon ,
Thank you for this PR. To reproduce the validation case, could tell which version of `pre-commit` you're using?
Thanks!

2024-12-05 21:56 UTC, Crocmagnon commented
version 4.0.1

2024-12-06 09:56 UTC, agateau-gg requested changes
Thanks! I finally managed to reproduce and I can confirm your changes fit the warning.

Looking at a [similar fix done by the pre-commit authors themselves](https://github.com/pre-commit/pre-commit-hooks/commit/003dfa55c9eb05b08b33f60864363392958f4618), it looks like it is recommended to add a `minimum_pre_commit_version: 3.2.0` entry for each hook. Can you look into this?

2024-12-06 17:16 UTC, agateau-gg approved these changes
Looks good, thanks!

2024-12-06 17:22 UTC, merged

2024-12-06 17:24 UTC, Crocmagnon commented
Thank you for your quick feedback! :)