feat(iac_scanning): add cli command
GitGuardian/ggshield pull request #232
Opened 2022-05-13 13:42 UTC by gg-mmill

Add iac scanning command.

2022-05-13 15:06 UTC, agateau-gg requested changes

2022-05-16 10:29 UTC, gg-mmill commented on ggshield/cmd/iac/scan.py
> +@click.option("--exclude", multiple=True, help="Do not scan the specified path.")
So [`banlist-detector`](https://github.com/GitGuardian/ggshield/blob/67aa70847105d9696696b0282d3d787db9bf8edb/ggshield/cmd/secret/scan/__init__.py#L73)  will be renamed as well ?

Do you have an insight about how short options should be named ? Having with multiple `ignore` options does not give us an obvious solution to this; here we have `ignore-path` and `ignore-policy`, which have the same initials :/

2022-05-16 10:34 UTC, gg-mmill commented
@agateau-gg There's an issue with mypy tests:  when running locally, I need to have `type: ignore` at `ggshield/cmd/iac/scan.py:41:` in order for the pre-commit hook to pass:
```mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

ggshield/cmd/iac/scan.py:41: error: Value of type variable "_PathType" of "Path" cannot be "Path"
Found 1 error in 1 file (checked 4 source files)
```
But then the CI fails: https://github.com/GitGuardian/ggshield/runs/6423956245?check_suite_focus=true

2022-05-17 13:27 UTC, agateau-gg commented on ggshield/cmd/iac/scan.py
> +@click.option("--exclude", multiple=True, help="Do not scan the specified path.")
Yes, `--banlist-detector` is supposed to become `--ignore-detector`.

We don't have a plan for short options yet :/. We might do what pytest does: provide "less-long" options only (I am referring to pytest options like `--lf` being an alias for `--last-failed`, assuming Click allows one to do that). In this case we could have `--ipa`, `--ipo` and `--ide`?

2022-05-18 07:30 UTC, gg-mmill commented on ggshield/cmd/iac/scan.py
> +@click.option("--exclude", multiple=True, help="Do not scan the specified path.")
Very well, updated the commands with 3-letters short options, click doesn't seem too mad about it :)

2022-05-18 08:37 UTC, agateau-gg commented on tests/cmd/iac/test_scan.py
> +        print(result.exception)
Can be removed ;)

2022-05-18 08:37 UTC, agateau-gg commented on ggshield/cmd/iac/scan.py
> +@click.option("--exclude", multiple=True, help="Do not scan the specified path.")
Mmm, pytest uses two dashes for its less-long options, I think we should do the same.

2022-05-18 09:29 UTC, gg-mmill commented on ggshield/cmd/iac/scan.py
> +@click.option("--exclude", multiple=True, help="Do not scan the specified path.")
In fact changed the "multiple" options again, so that: 
 - the option flag is singular
 - the assigned variable is plural

2022-05-18 10:21 UTC, agateau-gg approved these changes
Looks good!

2022-05-18 10:21 UTC, merged