docs(iac): add readme for iac section
GitGuardian/ggshield pull request #285
Opened 2022-07-05 15:32 UTC by GG-HH

Add a readme for the IaC section.

2022-07-06 10:39 UTC, agateau-gg requested changes

2022-07-06 10:39 UTC, agateau-gg commented on README.md
> +Reference for this command can be found in [GitGuardian documentation](https://docs.gitguardian.com/iac-scanning/cli_reference)
You might want to verify this is going to be the right URL: given that documentation for `ggshield secret scan` is https://docs.gitguardian.com/internal-repositories-monitoring/ggshield/reference/secret/scan/overview, I expect the doc for `ggshield iac scan` to be https://docs.gitguardian.com/internal-repositories-monitoring/ggshield/reference/iac/scan/overview.

2022-07-07 17:21 UTC, agateau-gg approved these changes

2022-07-07 17:22 UTC, agateau-gg commented
> Caution: this MR references ggshield tags and files that don't exist yet.

Is it still the case? It looks to me like this PR can be merged.

2022-07-07 17:23 UTC, GG-HH commented
Sorry, I forgot to update the description.

2022-07-07 17:23 UTC, merged