feat: Check for updates and display a warning when an update is available
GitGuardian/ggshield pull request #371
Opened 2022-10-05 15:33 UTC by Walz

When the command is called, look for updates by requesting the latest release on GitHub. Save the latest version in a local file to only query GitHub once per day.

closes #299

2022-10-06 09:32 UTC, agateau-gg commented on tests/unit/core/test_utils.py
> +):
You can use the `fs` fixture from [pyfakefs](https://pypi.org/project/pyfakefs/) in your test to ensure the test never touches the real file system. This avoids side-effects and removes the need for the optional `cache` argument in `check_for_update()`.

2022-10-07 10:12 UTC, Walz commented on ggshield/core/utils.py
> +        if resp.status_code == 200:
Even if the request to GitHub API fails, we may still return a warning if a new version has been cached.

2022-10-07 12:56 UTC, agateau-gg approved these changes
Looks good but... CI is not happy 😢 

I suspect the failures come from the fact that we execute the unit-test test-suite with `--disable-socket`, and since a lot of tests go through `cli()` we end up checking for updates a lot :).

This is, I think, a rare case where it makes sense for the main code to alter its behavior depending on whether it's being run by pytest. I think you can fix this by modifying `main.cli()` to not check for updates if the `PYTEST_CURRENT_TEST` environment variable is set. This looks a nice way to detect if the code is running under pytest without importing pytest in the code itself.

2022-10-10 07:33 UTC, agateau-gg requested changes
Minor remarks. Looks good otherwise.

2022-10-10 07:33 UTC, agateau-gg commented on ggshield/cmd/main.py
> +    if check_for_updates and "PYTEST_CURRENT_TEST" not in os.environ:
Can you add a comment explaining why we added the `PYTEST_CURRENT_TEST` check? Should help future-us being less puzzled about this code.

2022-10-10 07:33 UTC, agateau-gg commented on ggshield/core/check_updates.py
> +                f"(https://github.com/GitGuardian/ggshield)."
That's not exactly what I had in mind with "separation of concerns": the idea is this function does not need to concern itself with how the information is going to be presented to the user: it should return either None (no update available), or the version number of the available version. Then it's up to the caller to present the information, which in our case means including the version number in a text message.

2022-10-10 15:05 UTC, agateau-gg approved these changes
Looks good, thanks!

2022-10-10 15:05 UTC, merged