Simplify Readme
GitGuardian/ggshield pull request #438
Opened 2022-12-02 10:30 UTC by pierrelalanne

In this PR, we simplify `ggshield`'s README.md and we point to the [public documentation](https://docs.gitguardian.com/ggshield-docs/getting-started) instead when applicable.  

We keep the following sections in the README :
- How to install
- How to authenticate and start using the project
- A link to the doc
- Related open source project
- License

2022-12-02 11:14 UTC, agateau-gg requested changes
I think we need to wet the appetite of the reader a bit more.

(Disclaimer: I am not a marketing person, but I just pretend to be one in pull-request reviews!)

I suggest replacing the "Initial setup" and "Documentation" sections with this:

---
## Initial setup

To use `ggshield` you need to authenticate against GitGuardian servers. To do so, use the `ggshield auth login` command. This command automates the provisioning of a personal access token and its configuration on the local workstation.

You can learn more about it from [`ggshield auth login` documentation](https://docs.gitguardian.com/internal-repositories-monitoring/ggshield/reference/auth/login).

Alternatively, you can create your personal access token manually and you can store it in the `GITGUARDIAN_API_KEY` environment variable to complete the setup.

## Getting started

You can now use `ggshield` to search for secrets:

- in files: `ggshield secret scan path -r .`
- in repositories: `ggshield secret scan repo .`
- in Docker images: `ggshield secret scan docker ubuntu:22.04`
- in Pypi packages: `ggshield secret scan pypi flask`
- and more, have a look at `ggshield secret scan --help` output for details.

You can also search for issues in your IaC code:

```
ggshield iac scan .
```

## Integrations

You can integrate `ggshield` in your [CI/CD workflow](https://docs.gitguardian.com/ggshield-docs/integrations/overview#cicd-integrations-secrets-detection-in-your-cicd-workflow).

To catch errors earlier, use `ggshield` as a [pre-commit, pre-push or pre-receive Git hook](https://docs.gitguardian.com/ggshield-docs/integrations/overview#git-hooks-prevent-secrets-from-reaching-your-vcs).

## Learn more

For more information, have a look at [the documentation](https://docs.gitguardian.com/ggshield-docs/getting-started)

2022-12-02 11:14 UTC, agateau-gg commented on README.md
>  To update ggshield you can add the option `-U/--upgrade` to the pip install command.
```suggestion
To update ggshield you can add the option `-U/--upgrade` to the `pip install` command.
```

2022-12-05 11:33 UTC, pierrelalanne commented
I fully agree with your comment, I integrated your suggestion.  
I am still not convinced by the output section, but I think we should keep it until we include a nice demo of the tool in the README.

2022-12-05 16:25 UTC, agateau-gg commented
> I fully agree with your comment, I integrated your suggestion. I am still not convinced by the output section, but I think we should keep it until we include a nice demo of the tool in the README.

I agree. Let's merge this: it solves the issue of duplicated information. We can iterate on the README and add a demo later.

2022-12-05 16:25 UTC, merged