chore(cli): Remove the deprecated commands 'ggshield scan' and 'ggshield ignore'
GitGuardian/ggshield pull request #504
Opened 2023-04-03 12:16 UTC by Walz

# Description

Remove the deprecated CLI commands `ggshield scan` and `ggshield ignore` which have been replaced by `ggshield secret scan` and `ggshield secret ignore`.

# What has been done

- Removed the module `ggshield.cmd.scan` containing the code for `ggshield scan`.
- Removed the function for `ggshield ignore` and moved the implementation out of `ignore_cmd_impl` into the method for `ggshield secret ignore` as it's no longer used by two commands.
- Updated the test using the deleted commands.

2023-04-04 11:19 UTC, agateau-gg requested changes
Minor remarks. Interesting to see that our own test suite was not up to date 😅.

2023-04-04 11:19 UTC, agateau-gg commented on changelog.d/20230403_121625_samuel.guillaume_scrt_3269_ggshield_scan_removal.md
> +- Removed the deprecated commands `ggshield scan` and `ggshield ignore`.
When we remove commands, it's a good idea to remind the user of what to use instead. I suggest the following:
```suggestion
- The deprecated commands `ggshield scan` and `ggshield ignore` have been removed. Use `ggshield secret scan` and `ggshield secret ignore` instead.
```

2023-04-07 13:22 UTC, Walz commented on Pipfile.lock
It must be because I'm on a different architecture. I've reset the changes to the lock file.

2023-04-07 13:49 UTC, agateau-gg approved these changes

2023-04-07 14:16 UTC, merged