Prepare IaC files for a differential scan
GitGuardian/ggshield pull request #559
Opened 2023-06-09 10:12 UTC by Paul-GitGuardian

As #558 was getting too big, this PR (not functional as-is) will focus on the files part of the IaC diff scan functionality.

2023-06-09 15:23 UTC, cyrvan-b commented on tests/unit/core/test_git_shell.py
> +    # When creating a tar
```suggestion
    # WHEN creating a tar
```

2023-06-12 09:13 UTC, Paul-GitGuardian commented
@agateau-gg these are mostly changes that you've seen already in #558, with tests added.

2023-06-12 13:49 UTC, agateau-gg requested changes
The git_shell changes looks good overall, only a few nitpicks 👍🏻 .

There is one important aspect to take into account before we can merge this, though: we try to keep the `main` branch in an "always releasable" state. This means the changes to the existing `iac scan` cannot be merged until they are finished.

You have a few options here:

**Option A:**
- Create an integration branch from `main`. something like `main-iac` (it's better if it starts or ends with `main` because then it's easy to apply the CI protections to it).

- make all your PR target main-iac. We review them as they go.

- When your feature is ready to ship, we can file a PR to merge main-iac in main. Since all commits in main-iac have already been reviewed, it won't be necessary to thoroughly review the merge of main-iac into main.

To avoid diverging too much from main, it's a good idea to regularly merge main into main-iac. We have done this in the past.

**Option B:** Revert the changes made to the existing `iac scan` command for now. If necessary, create a hidden command for testing purposes (hidden in the Click-sense: by adding `hidden=True` to the command definition)

2023-06-12 13:49 UTC, agateau-gg commented on ggshield/core/git_shell.py
> +    :param filepaths: string paths to selected files
Can you document `acceptation_func`?

2023-06-12 13:49 UTC, agateau-gg commented on ggshield/core/git_shell.py
> +    The filepaths are typically obtained via `get_all_filepaths_from_reference`
```suggestion
    The filepaths are typically obtained via `get_filepaths_from_ref`
```

2023-06-12 13:49 UTC, agateau-gg commented on ggshield/core/git_shell.py
> +    filepaths: List[str],
nit: you can make `filepaths` an `Iterable[str]` (or even an `Iterable[Path]`, I would very much like to see more Path in the codebase 😉), this way one can use the return value of a generator as an argument.

2023-06-12 13:49 UTC, agateau-gg commented on tests/unit/core/test_git_shell.py
> +def test_check_git_ref(tmp_path):
This test should be split at least in two: one test for the not-in-a-repo part and another for the in-a-repo part.

There should be only one of GIVEN/WHEN/THEN in each test.

2023-06-12 13:49 UTC, agateau-gg commented on tests/unit/core/test_git_shell.py
> +    # THEN file from first commit is part of filepaths
```suggestion
    # AND staged file is part of filepaths
```

2023-06-12 13:49 UTC, agateau-gg commented on tests/unit/core/test_git_shell.py
> +        assert second_file_name not in filenames
Unless I am mistaken, this can be simplified as `assert filenames == [first_file_name]`, no?

2023-06-12 15:05 UTC, GG-HH reviewed
Sounds good overall!

2023-06-12 15:05 UTC, GG-HH commented on ggshield/cmd/iac/scan/scan.py
> +        else iac_diff_scan(ctx, directory, since, staged)
If I read correctly, the command is not correct, maybe that it on purpose and will be in another MR ?

2023-06-12 15:05 UTC, GG-HH commented on ggshield/core/git_shell.py
> +        raise UsageError("Not a git reference.")
Should we add the value (if existing) to help debugging ?

2023-06-12 15:35 UTC, Paul-GitGuardian commented
Thank you for the reviews!
Regarding the integration branch: option A is what I did, following your advice on another PR. The name was misleading though, so I renamed it based on your suggestion.

2023-06-13 12:26 UTC, GG-HH approved these changes

2023-06-13 15:18 UTC, merged