Refactor: Replace scan diff hook options by new commands
GitGuardian/ggshield pull request #615
Opened 2023-07-06 12:11 UTC by Paul-GitGuardian

Currently, the `iac scan diff` command handles three options to simplify git hooks: `--pre-commit`, `--pre-push` and `--pre-receive`. The objective of the `main-iac-cli-hooks` integration branch is to replace them with new `iac scan` subcommands.

This PR will refactor elements of the code in order to:
- make the implementation of the subcommands (not in the scope of this PR) easier
- factorize code

2023-07-06 16:37 UTC, GG-HH commented
Sounds good to me except the files that you asked not to review.

2023-07-07 12:36 UTC, agateau-gg requested changes
Minor remarks, looks good overall. Do you need the `main-iac-cli-hooks` branch though? It seems to me these changes could be merged into `main` directly.

2023-07-07 12:36 UTC, agateau-gg commented on ggshield/cmd/iac/scan/all.py
> +    result: Union[IaCScanResult, None],
nit: should be
```suggestion
    result: Optional[IaCScanResult],
```

2023-07-07 12:36 UTC, agateau-gg commented on ggshield/cmd/iac/scan/iac_scan_common_options.py
> +    help="Raise all vulnerabilities in the final state.",
wording:
```suggestion
    help="Report all vulnerabilities in the final state.",
```

2023-07-07 12:36 UTC, agateau-gg commented on ggshield/cmd/iac/scan/precommit.py
> +    # TODO: WIP
This comment can be removed: it does not tell readers what to do here.

2023-07-07 12:36 UTC, agateau-gg commented on ggshield/cmd/iac/scan/precommit.py
> +    # TODO: remove this once the GGClient is updated with the new diff function
I think this comment is no longer necessary?

2023-07-07 12:36 UTC, agateau-gg commented on ggshield/cmd/iac/scan/precommit.py
> +    staged = True
maybe inline those?

(this comment and the two previous ones apply to the other `scan_pre_*_cmd()` functions as well)

2023-07-07 13:27 UTC, Paul-GitGuardian commented
I agree regarding the branch, I expected it to be needed but it isn't. I've rebased on main directly.
Unfortunately, I can't edit the target branch in the PR, so I've created a new one (#619) and will close this one once the other is merged on main.

2023-07-07 13:27 UTC, closed without merging