Logout HMSL when calling GGshield auth logout
GitGuardian/ggshield pull request #616
Opened 2023-07-06 14:50 UTC by iXioN

Remove the JWT token when doing a ggshield logout

2023-07-06 17:36 UTC, pierrelalanne reviewed
A few remarks. Otherwise, looks good to me when testing.

2023-07-06 17:36 UTC, pierrelalanne commented on tests/unit/hmsl/test_hmsl_utils.py
> +    THEN the token as been removed
```suggestion
    THEN the token has been removed
```

2023-07-06 17:36 UTC, pierrelalanne commented on tests/unit/hmsl/test_hmsl_utils.py
> +    WHEN I want to remove the token
Nit ?
```suggestion
    WHEN I'm calling remove_token_from_disk
```

2023-07-06 17:36 UTC, pierrelalanne commented on ggshield/hmsl/utils.py
> +        if os.path.exists(TOKEN_PATH):
Nit: I would add an `except OSError` and pass instead of having an if.

2023-07-06 17:36 UTC, pierrelalanne commented on ggshield/hmsl/utils.py
> +TOKEN_PATH = "{}/hmsl_token".format(get_cache_dir())
f-strings are more concise:  
```suggestion
TOKEN_PATH = f"{get_cache_dir()}/hmsl_token"
```

2023-07-13 15:13 UTC, Walz requested changes
I've merged a fix for the tests, can you rebase and squash the branch. Also you are missing a changelog (`scriv create`).

2023-07-20 14:44 UTC, Walz approved these changes

2023-07-27 12:03 UTC, Walz approved these changes

2023-07-27 12:07 UTC, merged