Draft: feat(color): Enable color output in GitLab CI
GitGuardian/ggshield pull request #636
Opened 2023-07-17 12:12 UTC by gg-teolohrer

enables color output in CI.
Adds the option to disable color entirely with NO_COLOR (https://no-color.org/)

2023-07-17 12:23 UTC, GG-HH commented on ggshield/cmd/main.py
> +
Nit: use a helper function to insulate the color logic
Nit2: add a comment on why you try to check the GL_USERNAME

2023-07-21 14:22 UTC, GG-HH approved these changes

2023-07-21 14:51 UTC, gg-teolohrer commented
@Walz This change is project wide and changes output behavior for secret detection as well.

2023-07-24 08:11 UTC, Walz requested changes

2023-07-24 08:11 UTC, Walz commented on tests/conftest.py
> +def do_not_use_colors(monkeypatch, tmp_path):
```suggestion
def do_not_use_colors(monkeypatch):
```

2023-07-24 09:12 UTC, Walz approved these changes

2023-07-24 09:27 UTC, merged