feat(iac): github action should now use the new CI command
GitGuardian/ggshield pull request #646
Opened 2023-07-25 09:28 UTC by Paul-GitGuardian

Depends on #628 to be merged for the action-unstable, and deployed for the action to work.
This was not tested yet.

Updates the IaC Github Action to use the new `ggshield iac scan ci` command instead of `ggshield iac scan all`.

2023-07-25 09:30 UTC, Paul-GitGuardian commented
This changes the behavior of the action: it will now only block if new vulnerabilities are introduced.
Is it ok?

2023-07-26 07:35 UTC, gg-teolohrer commented on changelog.d/20230725_144801_paul.beslin.ext_update_github_action_iac_command.md
> +- The IaC Github Action now executes the new `ggshield iac scan ci` command. This means the action will fail only if the changes introduce a new vulnerability.
```suggestion
- The IaC Github Action now executes the new `ggshield iac scan ci` command. This means the action will fail only if the changes introduce a new vulnerability. To fail if any vulnerability is detected, use the `ggshield iac scan ci --all` command
```

2023-07-26 07:36 UTC, gg-teolohrer requested changes
The change in behavior seems OK to me, but we should describe the alternative in the changelog.

2023-07-26 07:54 UTC, cyrvan-b commented
LGTM with the change on changelogs.

2023-07-26 08:32 UTC, gg-teolohrer approved these changes

2023-07-31 07:40 UTC, cyrvan-b approved these changes

2023-08-04 11:28 UTC, GG-HH commented
@Paul-GitGuardian we should update the action files as well, the description will lack some options offered by the CI scan.

2023-08-11 14:56 UTC, GG-HH commented on docker/actions-iac-entrypoint.sh
> +ggshield iac scan ci -v ${args[@]}
```suggestion
ggshield iac scan ci ${args[@]}
```
We shouldn't have verbose enabled by default

2023-08-16 08:28 UTC, merged