fix: file content could not be found
GitGuardian/ggshield pull request #706
Opened 2023-08-21 15:00 UTC by cyrvan-b

In case of a scan launched on a directory within a repository, the related file content was not found.

2023-08-22 14:40 UTC, GG-HH requested changes

2023-08-22 14:40 UTC, GG-HH commented on tests/functional/iac/test_iac_scan_diff.py
> +    assert "The incident was found between" not in result.stdout
Maybe we should test the presence of parts of the `_IAC_SINGLE_VULNERABILITY` content ? That would be more robust, in particular if we change the wording of the fallback message.

2023-08-22 14:40 UTC, GG-HH commented on tests/functional/iac/test_iac_scan_diff.py
> +    assert "The incident was found between" not in result.stdout
And same below

2023-08-23 09:14 UTC, cyrvan-b commented on ggshield/iac/output/iac_text_output_handler.py
> +    def _get_source_path(self, scan: IaCPathScanCollection) -> Path:
After some tests it looks like their behavior is the same. Maybe calling `git rev-parse --show-toplevel` is less error prone as this is provided directly with git. I will propose a solution with that.

2023-08-23 13:39 UTC, GG-HH commented
Sounds good to me but there is a conflict with the main branch.

2023-08-25 08:32 UTC, GG-HH approved these changes

2023-08-25 15:36 UTC, merged