Amascia/sca 943/wrap commands
GitGuardian/ggshield pull request #720
Opened 2023-08-24 13:56 UTC by amascia-gg

Remove try/except blocks in commands from Secrets / IaC / SCA in favour of a decorator

2023-08-28 16:45 UTC, GG-HH reviewed
Ok to me, I am a bit confused by the `config: Config = args[0].obj["config"]` which seems a bit ugly to me.

2023-08-28 16:46 UTC, GG-HH commented
@agateau-gg WDYT ? Would you prefer if we remain with try/except blocks everywhere to be more explicit ?

2023-08-29 09:23 UTC, agateau-gg requested changes
I like the idea of reducing indentation level, and the fact that the decorate means a bit less boilerplate ✨.

Would be even better to wrap the call to `cli.main()` in `ggshield.__main__.main()` inside a try..except block instead of having to decorate all functions, but I am not sure this is possible.

"Request changes" because of a minor remark in the beta decorator.

2023-08-29 09:23 UTC, agateau-gg commented on ggshield/cmd/utils/common_decorators.py
> +
Should probably use `@wraps` here too, unless I am missing something.

2023-09-04 08:40 UTC, amascia-gg commented
> I like the idea of reducing indentation level, and the fact that the decorate means a bit less boilerplate ✨.
> 
> Would be even better to wrap the call to `cli.main()` in `ggshield.__main__.main()` inside a try..except block instead of having to decorate all functions, but I am not sure this is possible.
> 
> "Request changes" because of a minor remark in the beta decorator.

The context does not exist at this stage just yet so it was not possible unfortunately.

2023-09-04 09:48 UTC, agateau-gg approved these changes
Looks good, thanks!

2023-09-04 09:48 UTC, merged