feat(iac): add more scan modes based on context and --all flag
GitGuardian/ggshield pull request #760
Opened 2023-10-04 11:26 UTC by Paul-GitGuardian

Adds more details in the scan mode passed as header (for IAC):
- what triggered the scan (manually, pre-commit, pre-push, pre-receive, ci)
- how it was performed (all, diff)

2023-10-04 17:12 UTC, GG-HH commented
Sounds good to me, except one thing: in other verticals, when scanning in CI, we have access to the type of CI (see supported_ci.py). I don't think that would be the case here.

Could we add some tests as well to ensure that the flag can be found in the headers of the query in the end ?

2023-10-04 17:12 UTC, GG-HH requested changes
GH forces me to put a comment here. sorry.

2023-10-05 09:24 UTC, Paul-GitGuardian commented
> Sounds good to me, except one thing: in other verticals, when scanning in CI, we have access to the type of CI (see supported_ci.py). I don't think that would be the case here.
> 
> Could we add some tests as well to ensure that the flag can be found in the headers of the query in the end ?

Done for the CI mode.
I'm not sure how we can access request headers in tests, especially when the request is made in pygitguardian?

2023-10-05 17:13 UTC, GG-HH approved these changes

2023-10-09 09:56 UTC, merged