refactor(iac): change iac diff scan json output format
GitGuardian/ggshield pull request #790
Opened 2023-10-30 15:26 UTC by Paul-GitGuardian

Changes the format of the JSON output for an iac diff scan.

<details>
  <summary>Before</summary>

  ```json
{
    "added_vulns": [
        {
            "filename": "terraform/aws/s3.tf",
            "incidents": [
                {
                    "policy": "Allowing public exposure of a S3 bucket can lead to data leakage",
                    "policy_id": "GG_IAC_0055",
                    "line_end": 8,
                    "line_start": 1,
                    "description": "AWS S3 Block Public Access is a feature that allows setting up centralized controls\\nto manage public access to S3 resources.\\n\\nEnforcing the BlockPublicAcls, BlockPublicPolicy and IgnorePublicAcls rule on a bucket\\nallows to make sure that no ACL (Access control list) or policy giving public access\\ncan be associated with the bucket, and that existing ACL giving public access to\\nthe bucket will not be taken into account.",
                    "documentation_url": "<https://docs.gitguardian.com/iac-scanning/policies/GG_IAC_0055>",
                    "component": "aws_s3_bucket.test",
                    "severity": "HIGH"
                }
            ],
            "total_incidents": 1
        }
    ],
    "persisting_vulns": [
        {
            "filename": "terraform/aws/db-app.tf",
            "incidents": [
                {
                    "policy": "EC2 instances use unencrypted block device",
                    "policy_id": "GG_IAC_0033",
                    "line_end": 413,
                    "line_start": 243,
                    "description": "Amazon EBS provides durable, block-level storage volumes that you can attach\\nto a running instance. They will typically be used to host the filesystem\\nfor an application (except for the boot volume). As such, they will often host\\nconfiguration files, and sometimes the secrets needed by the application to\\naccess external services.\\n\\nEncrypting your volumes ensures that your application runtime data will not be\\ncompromised from raw access to the disks.",
                    "documentation_url": "<https://docs.gitguardian.com/iac-scanning/policies/GG_IAC_0033>",
                    "component": "aws_instance.db_app",
                    "severity": "HIGH"
                }
            ],
            "total_incidents": 1
        }
    ],
    "removed_vulns": []
}
  ```
</details>

<details>
  <summary>After</summary>

  ```json
{
    "id": "fb0e9a92-de34-43f9-b779-17d25e99ab35",
    "iac_engine_version": "1.15.0",
    "type": "diff_scan",
    "entities_with_incidents": {
        "unchanged": [
            {
                "filename": "s3.tf",
                "incidents": [
                    {
					    "policy": "Allowing public exposure of a S3 bucket can lead to data leakage",
                        "policy_id": "GG_IAC_0055",
                        "line_end": 118,
                        "line_start": 96,
                        "description": "AWS S3 Block Public Access is a feature that allows setting up centralized controls\\nto manage public access to S3 resources.\\n\\nEnforcing the BlockPublicAcls, BlockPublicPolicy and IgnorePublicAcls rule on a bucket\\nallows to make sure that no ACL (Access control list) or policy giving public access\\ncan be associated with the bucket, and that existing ACL giving public access to\\nthe bucket will not be taken into account.",
                        "documentation_url": "<https://docs.gitguardian.com/iac-scanning/policies/GG_IAC_0055>",
                        "component": "aws_s3_bucket.operations",
                        "severity": "HIGH"
                    }
                ],
                "total_incidents": 1
            }
        ],
        "deleted": [
          {
            "filename": "s3.tf",
                "incidents": [
                    {
		                "policy": "Allowing public exposure of a S3 bucket can lead to data leakage",
                        "policy_id": "GG_IAC_0055",
                        "line_end": 118,
                        "line_start": 96,
                        "description": "AWS S3 Block Public Access is a feature that allows setting up centralized controls\\nto manage public access to S3 resources.\\n\\nEnforcing the BlockPublicAcls, BlockPublicPolicy and IgnorePublicAcls rule on a bucket\\nallows to make sure that no ACL (Access control list) or policy giving public access\\ncan be associated with the bucket, and that existing ACL giving public access to\\nthe bucket will not be taken into account.",
                        "documentation_url": "<https://docs.gitguardian.com/iac-scanning/policies/GG_IAC_0055>",
                        "component": "aws_s3_bucket.operations",
                        "severity": "HIGH",
                    }
                ],
                "total_incidents": 1
            }
        ],
        "new": [
          {
            "filename": "s3.tf",
                "incidents": [
                    {
			            "policy": "Allowing public exposure of a S3 bucket can lead to data leakage",
                        "policy_id": "GG_IAC_0055",
                        "line_end": 118,
                        "line_start": 96,
                        "description": "AWS S3 Block Public Access is a feature that allows setting up centralized controls\\nto manage public access to S3 resources.\\n\\nEnforcing the BlockPublicAcls, BlockPublicPolicy and IgnorePublicAcls rule on a bucket\\nallows to make sure that no ACL (Access control list) or policy giving public access\\ncan be associated with the bucket, and that existing ACL giving public access to\\nthe bucket will not be taken into account.",
                        "documentation_url": "<https://docs.gitguardian.com/iac-scanning/policies/GG_IAC_0055>",
                        "component": "aws_s3_bucket.operations",
                        "severity": "HIGH"
                    }
                ],
                "total_incidents": 1
            }
        ]
    }
}
  ```
</details>

2023-11-02 12:20 UTC, GG-HH requested changes

2023-11-02 12:20 UTC, GG-HH commented on tests/unit/verticals/iac/output/test_iac_diff_json_output.py
> +    #                     "policy_id": "POLICY_ID",
Should be removed

2023-11-02 13:15 UTC, GG-HH commented
And it lacks a changelog. This is a customer facing change that should be "changeloged"

2023-11-03 14:09 UTC, Paul-GitGuardian commented
> And it lacks a changelog. This is a customer facing change that should be "changeloged"

I also added an example inside a collapsible section, I assume these work in the Github changelog ?

2023-11-08 09:33 UTC, GG-HH approved these changes

2023-11-08 09:34 UTC, merged