WIP: Implement pre-commit framework SKIP environment variable.
GitGuardian/ggshield pull request #794
Opened 2023-11-08 08:20 UTC by irgeek

When `ggshield` is configured via the [pre-commit framework](https://pre-commit.com/) the user has the option to skip specific scans by setting the `SKIP` environment variable. When `ggshield` is configured directly as a `git` pre-commit hook, though, the user only has the option to disable _all_ pre-commit hooks via the `--no-verify` command-line option. Here we're "borrowing" the pre-commit framework's option so ggshield can be skipped the same way regardless of how it's configured.

2023-11-08 10:33 UTC, agateau-gg requested changes
I like the idea but I would make a few changes to the implementation.

SKIP can apply to pre-push as well pre-commit, and it can apply to all verticals not only scan. For these reasons, I suggest the following:

1. add a `cmd.utils.hooks` module with a `check_user_requested_skip() -> bool` function in it, which would:
- read the env var
- print the info message if user requested skipping
- return True or False

2. Then make all precommit/prepush commands use this function.

2023-11-08 15:58 UTC, irgeek commented
@agateau-gg I've relocated my first implementation into a hooks module. Before I go scribbling in other files to add the check, can you just confirm this looks OK?

2023-11-09 08:43 UTC, agateau-gg requested changes
Minor remarks, this is going in the right direction 👍🏻.

2023-11-09 08:43 UTC, agateau-gg commented on ggshield/cmd/utils/hooks.py
> +def get_skip_env_var() -> bool:
I think you can merge these two, unless `check_user_requested_skip()` becomes responsible for showing the message.

2023-11-09 08:43 UTC, agateau-gg commented on ggshield/cmd/utils/hooks.py
> +        skip_env_var = os.getenv("SKIP", None)
nit: None is the default default value :)
```suggestion
        skip_env_var = os.getenv("SKIP")
```

2023-11-09 08:43 UTC, agateau-gg commented on ggshield/cmd/utils/hooks.py
> +        display_error(f"Unable to parse SKIP environment variable: {str(e)}")
I don't think we need to wrap the whole function like this: there's not really code which can fail there.

On the other hand, can you add a unit-test for this function?

2023-11-09 08:43 UTC, agateau-gg commented on ggshield/cmd/secret/scan/precommit.py
> +        click.echo("Skipping GitGuardian pre-receive hook.", err=False)
This is pre-commit here, not pre-receive ;). Actually if we make the message more generic (like "Skipping ggshield hook"), we can make `check_user_requested_skip()` print it and avoid duplicating the message in all hooks of all verticals.

2023-11-16 15:08 UTC, agateau-gg requested changes
Looks good overall, thanks :+1:.

Just some minor remarks. It also needs a changelog entry (see https://github.com/GitGuardian/ggshield/blob/main/doc/dev/getting-started.md#changelog for details about the changelog entry)

2023-11-16 15:08 UTC, agateau-gg commented on tests/unit/cmd/utils/test_hooks.py
> +    pass
This line can be removed

2023-11-16 15:08 UTC, agateau-gg commented on ggshield/cmd/utils/hooks.py
> +    return False
You can simplify this a bit using an early return and `any`:

```suggestion
    if skip_env_var is None:
        return False
        
    return any(p.strip().lower() == "ggshield" for p in skip_env_var.split(","))
```

2023-11-23 08:35 UTC, agateau-gg commented
As you pointed out, the lint check fails because the PR comes from a fork of the repository. Therefore I am merging it. Will look into that lint bug later.

2023-11-23 08:35 UTC, merged

2023-11-23 09:12 UTC, StanislasGG commented
Hello Aurelien, can you confirm that this will be included in next week's release ?

Thanks in advance

2023-11-23 09:18 UTC, agateau-gg commented
> Hello Aurelien, can you confirm that this will be included in next week's release ?
> 
> Thanks in advance

Yes, it will be there.