Implement auto-ignore
GitGuardian/ggshield pull request #800
Opened 2023-11-15 16:12 UTC by Paul-GitGuardian

The API now returns the status of each IaC incident on the GitGuardian app. We should use it to display only incidents that were not ignored on the app.

This applies to all IaC scan commands (all, diff, ci...) in all formats (text, JSON).

2023-11-27 12:15 UTC, Paul-GitGuardian commented
Hello @agateau-gg, the changes of this PR do not pass the tests yet as they require the typing changes in https://github.com/GitGuardian/py-gitguardian/pull/80. You can either review the code now or wait for the pygitguardian release. Thanks!

2023-11-28 17:29 UTC, agateau-gg requested changes
CI is unhappy. To fix it:
- Follow instructions from https://github.com/GitGuardian/ggshield/blob/main/doc/dev/dependencies.md#using-an-unreleased-version-of-py-gitguardian
- Replace `type[IaCOutputHandler]` with `Type[IaCOutputHandler]`.

2023-12-05 09:45 UTC, agateau-gg approved these changes
Looks good now 👍🏻.

2023-12-05 10:22 UTC, merged

2023-12-05 10:24 UTC, Paul-GitGuardian commented
Thank you for your comments