Add incident details option for json and sarif formats
GitGuardian/ggshield pull request #956
Opened 2024-09-06 16:18 UTC by fnareoh

## Context

- Add `--with-incident-details` to output (json and sarif output only) more information about incident when the secret is already known by the gitguardian dashboard.

## What has been done

## Validation

## PR check list

- [ ] As much as possible, the changes include tests (unit and/or functional)
- [ ] If the changes affect the end user (new feature, behavior change, bug fix) then the PR has a changelog entry (see doc/dev/getting-started.md). If the changes do not affect the end user, then the `skip-changelog` label has been added to the PR.

2024-09-09 14:29 UTC, agateau-gg commented on tests/unit/verticals/secret/output/test_json_output.py
> +    # add known_secret for the secrets that are known, when the option is, the known_secret field is not returned
I don't understand this comment, maybe a word is missing?

2024-09-09 14:32 UTC, agateau-gg commented on tests/unit/verticals/secret/output/test_json_output.py
> +@pytest.mark.parametrize("verbose", [True, False])
If I am not mistaken, the behavior does not depend on whether verbose is enabled or not, maybe we can remove this?

2024-09-09 14:37 UTC, agateau-gg commented on changelog.d/20240906_141336_fnareoh_scrt_4693_ggshield_output_expose_incident_date_and_severity.md
> +- Add `--with-incident-details` to output (json and sarif output only) more information about incident when the secret is already known by the gitguardian dashboard.
```suggestion
- Add `--with-incident-details` to output more information about known incidents (JSON and SARIF outputs only).
```

2024-09-09 14:38 UTC, agateau-gg commented on ggshield/cmd/secret/scan/secret_scan_common_options.py
> +    help="Display full details about the dashboard incident if one is found (json and sarif format only).",
```suggestion
    help="Display full details about the dashboard incident if one is found (JSON and SARIF formats only).",
```

2024-09-10 09:55 UTC, fnareoh commented on ggshield/verticals/secret/output/secret_sarif_output_handler.py
> +            dct["incidentDetails"] = incident_details[
Sorry I should have looked into that before. I get the impression that for any additional information, the key `properties` is used as a catch all [(github did this for their tag and precision additional fields)](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning), what do you think of having the incident details nested in properties ?

2024-09-10 10:12 UTC, agateau-gg commented on ggshield/verticals/secret/output/secret_sarif_output_handler.py
> +            dct["incidentDetails"] = incident_details[
Yes [property bags](https://github.com/microsoft/sarif-tutorials/blob/main/docs/2-Basics.md#property-bags) would be appropriate.

2024-09-10 11:36 UTC, fnareoh commented on ggshield/verticals/secret/output/secret_json_output_handler.py
> +                ]
Unfortunately this does not work due to [the Base class in pygitguardian having a weird __bool__ definition](https://github.com/GitGuardian/py-gitguardian/blob/215f5294a8efd4cb7e0c89472f00d955587b341e/pygitguardian/models.py#L81) :'(

2024-09-12 12:00 UTC, agateau-gg requested changes

2024-09-12 12:00 UTC, agateau-gg commented on ggshield/verticals/secret/secret_scan_collection.py
> +                    if type(resp) == SecretIncident:
That's a good idea, but maybe you can put it in `core.errors`?

2024-09-13 08:20 UTC, fnareoh commented on ggshield/verticals/secret/secret_scan_collection.py
> +        incidents_url_with_details: dict[str, SecretIncident] = {}
Arf sorry !

2024-09-13 13:38 UTC, fnareoh commented on ggshield/verticals/secret/output/secret_json_output_handler.py
> +            if self.with_incident_details and self.client
I added an assert before but pyright does not really get it so I had to leave the "and self.client"

2024-09-13 14:35 UTC, agateau-gg requested changes

2024-09-13 15:02 UTC, agateau-gg approved these changes

2024-09-18 16:16 UTC, merged